# Starship Configuration
format = """$username@$hostname $directory$git_branch$git_status $character"""
add_newline = false
[directory]
truncation_length = 3
truncate_to_repo = false
[directory.substitutions]
"Documents" = "ğŸ“„"
"Downloads" = "ğŸ“¥"
"Projects" = "ğŸš€"
[git_branch]
symbol = "ğŸŒ± "
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

